spring.application.name=finance-service
server.port=8084

# MySQL konekcija
spring.datasource.url=jdbc:mysql://localhost:3306/autoskola_finance_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true