server.port=8080
spring.application.name=gateway-service

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ===== USER-SERVICE =====
spring.cloud.gateway.routes[12].id=user-service-auth
spring.cloud.gateway.routes[12].uri=lb://user-service
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/auth/**

# ===== USER-SERVICE =====
spring.cloud.gateway.routes[13].id=user-service-register
spring.cloud.gateway.routes[13].uri=lb://user-service
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/users/register
spring.cloud.gateway.routes[13].order=-1

# ===== USER-SERVICE =====
spring.cloud.gateway.routes[0].id=user-service-users
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter
spring.cloud.gateway.routes[0].order=1


spring.cloud.gateway.routes[1].id=user-service-announcements
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/announcements/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter


# ===== TRAINING-SERVICE =====
spring.cloud.gateway.routes[2].id=training-lessons
spring.cloud.gateway.routes[2].uri=lb://training-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/lessons/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[4].id=training-candidates
spring.cloud.gateway.routes[4].uri=lb://training-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/candidates/**
spring.cloud.gateway.routes[4].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[5].id=training-feedbacks
spring.cloud.gateway.routes[5].uri=lb://training-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/feedbacks/**
spring.cloud.gateway.routes[5].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[6].id=training-rules
spring.cloud.gateway.routes[6].uri=lb://training-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/rules/**
spring.cloud.gateway.routes[6].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[7].id=training-phases
spring.cloud.gateway.routes[7].uri=lb://training-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/phases/**
spring.cloud.gateway.routes[7].filters[0]=AuthenticationFilter

# ===== FINANCE-SERVICE =====
spring.cloud.gateway.routes[8].id=finance-payments
spring.cloud.gateway.routes[8].uri=lb://finance-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/payments/**
spring.cloud.gateway.routes[8].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[9].id=finance-accounts
spring.cloud.gateway.routes[9].uri=lb://finance-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/accounts/**
spring.cloud.gateway.routes[9].filters[0]=AuthenticationFilter

# ===== RESOURCE-SERVICE =====
spring.cloud.gateway.routes[10].id=resource-vehicles
spring.cloud.gateway.routes[10].uri=lb://resource-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/vehicles/**
spring.cloud.gateway.routes[10].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[11].id=resource-repairs
spring.cloud.gateway.routes[11].uri=lb://resource-service
spring.cloud.gateway.routes[11].predicates[0]=Path=/repairs/**
spring.cloud.gateway.routes[11].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[3].id=resource-instructors
spring.cloud.gateway.routes[3].uri=lb://resource-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/instructors/**
spring.cloud.gateway.routes[3].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[14].id=training-theory-lessons
spring.cloud.gateway.routes[14].uri=lb://training-service
spring.cloud.gateway.routes[14].predicates[0]=Path=/api/theory-lessons/**
spring.cloud.gateway.routes[14].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[15].id=training-driving-lessons
spring.cloud.gateway.routes[15].uri=lb://training-service
spring.cloud.gateway.routes[15].predicates[0]=Path=/api/driving-lessons/**
spring.cloud.gateway.routes[15].filters[0]=AuthenticationFilter


jwt.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAklE7SIwSQ48kNeHigE1HkA1eNfSz5gnEixi7jt1GdgZzfKyWbMlztV9I8ZCx5sGuZTbRPP6P0qRPRbIhWbyTErC1tfNSF1QI/sdByZvDei9LBV/J0qivNq7yojsMGUiGBYc3x5lj//rudc12ohw7EtMmN7sBwWgWTrNJax1Fc3a0QNETZpBHJp7jMHVzXrqEiR78GTsq5y1lxFtdR0g12u56t1XQmVcUDx+jT5loqI3ZoG0ymVRHq3ZLP+294aBo8G8nNl8CxxTOWaZSqW/jKFFKQHTLrD1UH39JxbUFO8DPD1uq5x7dQkNMb3Bf5hedMurpTzQeOtPRzr/gElb4JwIDAQAB

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true


