server.port=8080
spring.application.name=gateway-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.routes[0].id=training-route
spring.cloud.gateway.routes[0].uri=lb://training-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**
