spring.application.name=user-service
server.port=8081

# Baza podataka
spring.datasource.url=jdbc:mysql://localhost:3306/autoskola_user_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

#Tokeni
jwt.expiration=3600000
jwt.private.key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSUTtIjBJDjyQ14eKATUeQDV419LPmCcSLGLuO3UZ2BnN8rJZsyXO1X0jxkLHmwa5lNtE8/o/SpE9FsiFZvJMSsLW181IXVAj+x0HJm8N6L0sFX8nSqK82rvKiOwwZSIYFhzfHmWP/+u51zXaiHDsS0yY3uwHBaBZOs0lrHUVzdrRA0RNmkEcmnuMwdXNeuoSJHvwZOyrnLWXEW11HSDXa7nq3VdCZVxQPH6NPmWiojdmgbTKZVEerdks/7b3hoGjwbyc2XwLHFM5ZplKpb+MoUUpAdMusPVQff0nFtQU7wM8PW6rnHt1CQ0xvcF/mF50y6ulPNB4609HOv+ASVvgnAgMBAAECggEBAIW+TMM+jf9FG2NJS6Hdgdlx7rjBKaPPL+G5RNANATgnI29FzuY3qlWSeHmeuo7kYUXROqdXRR3U5UUe0w9UqNb/wclEVbhPLz274y2m/KJ2EkwiR7gQSsBgYBbchG2j9iWdeOYxFtBIjaoOmi8KQREvApMUlEE2pJVhmm2XvwEPkAr5aZqZt1IuxIHU6kf0OsiAK2oH+qscYOkfWZQID+r41+Di/A/iw2tc0E7yJcGzOTbIH5+z4rnONx4Qwu40jAy3MWFRCXCt21FnnK7y0V91o4vCEOM9WcLukmJsY7nXvP6cWgLi+xWloXzs+N+9PjdtCyhxwOfO27ma4s4FVIkCgYEA0uHoc21sHptLkufzguDd7VW4g4U67j4wxTjwEVJakfbKhqDAlikzDXB9sysvpwfWJT36StCxbP75+JHSs7S3oHNWjyE1pm4cERFBlQTtQZX/osxCmu0G5UMPQlKoDd42kooBSqTV/AZ5WHziPk6QliAvpODXNYYiZjMvf2jElLUCgYEAsZ8ShOe9C4hHMgq3WSpphEmoEY2oT/Z7Jotkcpqi7qi04Qi80mSxZNxzeFvjjOuAtLauWN0hHX6W1wbxOE6pweo9DxHoXxRY+zvO/aOfoACEltHrGnbEtETbhqTWTMTaPouG01qxz0/3CGS7Fq3FKd1Wj7W2aQjdFGka3W8oXusCgYBj+CwV7B2BNOVSsxrBRJBwXl6mGpahMmI0XJWR4JSG9ZN01uf1R3qoOFeehC6G5DQkW4k3xk8V+JnPuHFGN7mFGqhCGeAxEanEfYW1eyxuFwmkx2gbwZmvPWcSbdS1Hk6IkVujYxj97KPByxIFr4Djakarxtq+yOOtxz4RDD2EsQKBgCYrG6ypq6sFvt7XBK1JeuEtfss+2JNOUQpoW85wwmBsqmnNGd5QOvqEkN+lR1Gp7b9nnjGEWzBeWoWcfUtvQ/Vio3pQi9GaqsBaCtHgTlXwpo1OUKogKYbfYRke5NocVxWnn/JdA+abtWb9VmK6NqsXYBmDn84UVIWlTFuXHmK/AoGAAVLavCMk7hoW+HidIss3kkg6FEVTQhDqKuECVB5M7iFiNBiZKzqFpaDpWyyC6Ew4v/a/VWxvgzqdNBZ80G39UrJwxSUjSAKKET7jZsSx2Hrq1CDGR2U/sPQ7I/Zgr6B2WzTDYuD2bigSzEx8xL1EbBPexvFFRsZWw4atoU7C0/s=
jwt.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAklE7SIwSQ48kNeHigE1HkA1eNfSz5gnEixi7jt1GdgZzfKyWbMlztV9I8ZCx5sGuZTbRPP6P0qRPRbIhWbyTErC1tfNSF1QI/sdByZvDei9LBV/J0qivNq7yojsMGUiGBYc3x5lj//rudc12ohw7EtMmN7sBwWgWTrNJax1Fc3a0QNETZpBHJp7jMHVzXrqEiR78GTsq5y1lxFtdR0g12u56t1XQmVcUDx+jT5loqI3ZoG0ymVRHq3ZLP+294aBo8G8nNl8CxxTOWaZSqW/jKFFKQHTLrD1UH39JxbUFO8DPD1uq5x7dQkNMb3Bf5hedMurpTzQeOtPRzr/gElb4JwIDAQAB

spring.rabbitmq.addresses=amqps://bmuhutky:Uc-Kpsd7HZiAJCNn7eAKbsWqEPsODJnF@kebnekaise.lmq.cloudamqp.com/bmuhutky