spring.application.name=resource-service
server.port=8082

#spring.rabbitmq.addresses=amqps://bmuhutky:Uc-Kpsd7HZiAJCNn7eAKbsWqEPsODJnF@kebnekaise.lmq.cloudamqp.com/bmuhutky

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/autoskola_resource_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#spring.jpa.properties.hibernate.generate_statistics=true
#logging.level.org.hibernate.stat=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true




user.service.url=http://localhost:8081

jwt.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAklE7SIwSQ48kNeHigE1HkA1eNfSz5gnEixi7jt1GdgZzfKyWbMlztV9I8ZCx5sGuZTbRPP6P0qRPRbIhWbyTErC1tfNSF1QI/sdByZvDei9LBV/J0qivNq7yojsMGUiGBYc3x5lj//rudc12ohw7EtMmN7sBwWgWTrNJax1Fc3a0QNETZpBHJp7jMHVzXrqEiR78GTsq5y1lxFtdR0g12u56t1XQmVcUDx+jT5loqI3ZoG0ymVRHq3ZLP+294aBo8G8nNl8CxxTOWaZSqW/jKFFKQHTLrD1UH39JxbUFO8DPD1uq5x7dQkNMb3Bf5hedMurpTzQeOtPRzr/gElb4JwIDAQAB